name: Cache App Data

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行
  workflow_dispatch:  # 允许手动触发

jobs:
  cache-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Generate app data
      run: |
        # 这里可以添加生成或更新apps.json的逻辑
        # 例如从外部API获取数据，或者处理用户提交的数据
        echo "数据生成完成"

    - name: Cache app data
      uses: actions/cache@v3
      with:
        path: data/apps.json
        key: app-data-${{ github.sha }}
        restore-keys: |
          app-data-

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        keep_files: true
